ci: fix mint install step to check Mintfile and use mint bootstrap

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,7 +14,13 @@ jobs:
       - name: Install Mint
         run: brew install mint
       - name: Install mint packages
-        run: mint install --verbose
+        run: |
+          if [ -f Mintfile ]; then
+            mint bootstrap --verbose
+          else
+            echo "::error::Mintfile not found! Ensure that it exists in the repository root."
+            exit 1
+          fi
       - name: Generate Xcode project
         run: xcodegen
       - name: Lint
